Create logout button
googleinterns/step196-2020 pull request #59
Opened 2020-08-20 21:35 UTC by gannerr

Create logout button

2020-08-21 17:12 UTC, terencedignon requested changes
hey, nice work! had two questions but otherwise LGTM

2020-08-24 15:18 UTC, graceehuu approved these changes

2020-08-25 14:26 UTC, terencedignon approved these changes

2020-08-25 14:27 UTC, terencedignon commented on capstone/src/main/webapp/index.html
> +    <link rel="stylesheet" href="index.css">
You can change the diffbase by changing the merging from 'master' to your other PR, this way only the relevant diffs are shown. I'd recommend that when one PR depends on another, or shares the same changes.

2020-08-25 14:28 UTC, terencedignon commented on capstone/src/main/webapp/index.html
> +    <link rel="stylesheet" href="index.css">
(just be sure to change it back to master when the other is merged)

2020-08-25 15:30 UTC, merged